### ISSUE TITLE
Compatibility with ethereal mapgen

### ISSUE THREAD

**Issue by 3raven** [minetest-mods/nether#46]
Hi,
I used the nether mod with the ethereal mapgen mod and the nether is formed of default stone and ores with few nether nodes.

**Comment by Treer** [comment]
there was a fix for Ethereal merged 6 days ago, so using the latest version from this repo should work.

That fix isn't on ContentDB yet, you'd have to either use git or download the latest version from [here](https://github.com/minetest-mods/nether/archive/refs/heads/master.zip).

The problem was that Ethereal deletes the biomes of every other mod. Let me know if the latest version isn't fixing it for you.

**Comment by 3raven** [comment]
Hi again,
I downloaded both last versions of ethereal and nether and now the nether works fine (even with dfcaverns activated !)
Thanks a lot

**Comment by Treer** [comment]
Note for later: Sounds like TenPlus1 fixed Ethereal, and so that dependency can come out:
https://forum.minetest.net/viewtopic.php?p=413642#p413642
