### ISSUE TITLE
Not sure if this is an issue, tried the mod but it dried up the nearby oceans

### ISSUE THREAD

**Issue by mightyjoe781** [minetest-mods/nether#54]
Server : multicraft
mapgen : v7

----------
Installed the mod correctly.
All nether stuff works fine.
Issue is where-ever i marked the spawn was surrounded by a large ocean. Now after installing mod that ocean is being replaced by air as i move around the ocean. Is this a bug or expected behaviour ?? or Mapgen is doing something nasty with oceans/water bodies on surface ?

**Comment by Treer** [comment]
I haven't used multicraft or tested against it, is it possible they're not 100% compatible with Minetest 5?

Nether mapgen won't affect areas that have already been emerged (unless you've set the backend database to dummy so that the land is regenerated every time the server starts), so the first thing I'd do is make absolutely sure nether is the cause - what happens to oceans if you disable nether (and only nether)?

If it is nether, you could try commenting out this line:
https://github.com/minetest-mods/nether/blob/master/mapgen.lua#L189

That line affects cave water in the nether biome, so wouldn't normally affect the ocean, but perhaps multicraft implements it oddly?

**Comment by mightyjoe781** [comment]
Hello thanks for your response from what I tested found out there was another mod/patch that was registering an ABM for removing water from nether but it was behaving weirdly (there were correct ranges of y given) and removing water on surface.
